CREATE INDEX IDX_VISIT_OCC_POS_CID ON VISIT_OCCURRENCE (PLACE_OF_SERVICE_CONCEPT_ID ASC);
CREATE INDEX IDX_VISIT_POS_SOURCE_VALUE ON VISIT_OCCURRENCE (PLACE_OF_SERVICE_SOURCE_VALUE ASC);
CREATE INDEX IDX_VISIT_VISIT_START_DATE ON VISIT_OCCURRENCE (VISIT_START_DATE ASC);
CREATE INDEX IDX_VISIT_VISIT_END_DATE ON VISIT_OCCURRENCE (VISIT_END_DATE ASC);
CREATE INDEX IDX_VISIT_OCC_PERSON_ID ON VISIT_OCCURRENCE (PERSON_ID ASC);

CREATE INDEX IDX_COHORT_COHORT_CID ON COHORT (COHORT_CONCEPT_ID ASC);
CREATE INDEX IDX_COHORT_COHORT_START_DATE ON COHORT (COHORT_START_DATE ASC);
CREATE INDEX IDX_COHORT_COHORT_END_DATE ON COHORT (COHORT_END_DATE ASC);
CREATE INDEX IDX_COHORT_SUBJECT_ID ON COHORT (SUBJECT_ID ASC);

CREATE INDEX IDX_PROC_OCC_PROC_OCC_ID ON PROCEDURE_OCCURRENCE (PROCEDURE_OCCURRENCE_ID ASC);
CREATE INDEX IDX_PROC_OCC_PROC_TYPE_CID ON PROCEDURE_OCCURRENCE (PROCEDURE_TYPE_CONCEPT_ID ASC);
CREATE INDEX IDX_PROC_OCC_PROC_SOURCE_VALUE ON PROCEDURE_OCCURRENCE (PROCEDURE_SOURCE_VALUE ASC);
CREATE INDEX IDX_PROC_OCC_PROC_DATE ON PROCEDURE_OCCURRENCE (PROCEDURE_DATE ASC);
CREATE INDEX IDX_PROC_OCC_PERSON_ID ON PROCEDURE_OCCURRENCE (PERSON_ID ASC);

CREATE INDEX IDX_PROC_COST_PROC_OCC_ID ON PROCEDURE_COST (PROCEDURE_OCCURRENCE_ID ASC);
CREATE INDEX IDX_PROC_COST_DC_CID ON PROCEDURE_COST (DISEASE_CLASS_CONCEPT_ID ASC);
CREATE INDEX IDX_PROC_COST_DC_SOURCE_VALUE ON PROCEDURE_COST (DISEASE_CLASS_SOURCE_VALUE ASC);

CREATE INDEX IDX_PROVIDER_PROVIDER_ID ON PROVIDER (PROVIDER_ID ASC);
CREATE INDEX IDX_PROVIDER_SP_CID ON PROVIDER (SPECIALTY_CONCEPT_ID ASC);
CREATE INDEX IDX_PROVIDER_SP_SOURCE_VALUE ON PROVIDER (SPECIALTY_SOURCE_VALUE ASC);

CREATE INDEX IDX_PERSON_PERSON_ID ON PERSON (PERSON_ID ASC);

CREATE INDEX IDX_OBS_OBS_PERIOD_START_DATE ON OBSERVATION_PERIOD (OBSERVATION_PERIOD_START_DATE ASC);
CREATE INDEX IDX_OBS_OBS_PERIOD_END_DATE ON OBSERVATION_PERIOD (OBSERVATION_PERIOD_END_DATE ASC);
CREATE INDEX IDX_OBS_PERIOD_PERSON_ID ON OBSERVATION_PERIOD (PERSON_ID ASC);

CREATE INDEX IDX_OBS_OBS_CID ON OBSERVATION (OBSERVATION_CONCEPT_ID ASC);
CREATE INDEX IDX_OBS_OBS_DATE ON OBSERVATION (OBSERVATION_DATE ASC);
CREATE INDEX IDX_OBS_PERSON_ID ON OBSERVATION (PERSON_ID ASC);

CREATE INDEX IDX_RX_ERA_RX_CID ON DRUG_ERA (DRUG_CONCEPT_ID ASC);
CREATE INDEX IDX_RX_ERA_RX_ERA_START_DATE ON DRUG_ERA (DRUG_ERA_START_DATE ASC);
CREATE INDEX IDX_RX_ERA_RX_ERA_END_DATE ON DRUG_ERA (DRUG_ERA_END_DATE ASC);
CREATE INDEX IDX_RX_ERA_PERSON_ID ON DRUG_ERA (PERSON_ID ASC);

CREATE INDEX IDX_RX_EXP_RX_CID ON DRUG_EXPOSURE (DRUG_CONCEPT_ID ASC);
CREATE INDEX IDX_RX_EXP_RX_SOURCE_VALUE ON DRUG_EXPOSURE (DRUG_SOURCE_VALUE ASC);
CREATE INDEX IDX_RX_EXP_RX_EXP_START_DATE ON DRUG_EXPOSURE (DRUG_EXPOSURE_START_DATE ASC);
CREATE INDEX IDX_RX_EXP_RX_EXP_END_DATE ON DRUG_EXPOSURE (DRUG_EXPOSURE_END_DATE ASC);
CREATE INDEX IDX_RX_EXP_PERSON_ID ON DRUG_EXPOSURE (PERSON_ID ASC);

CREATE INDEX IDX_DEATH_DEATH_DATE ON DEATH (DEATH_DATE ASC);
CREATE INDEX IDX_DEATH_PERSON_ID ON DEATH (PERSON_ID ASC);

CREATE INDEX IDX_DX_ERA_DX_CID ON CONDITION_ERA (CONDITION_CONCEPT_ID ASC);
CREATE INDEX IDX_DX_ERA_DX_ERA_START_DATE ON CONDITION_ERA (CONDITION_ERA_START_DATE ASC);
CREATE INDEX IDX_DX_ERA_DX_ERA_END_DATE ON CONDITION_ERA (CONDITION_ERA_END_DATE ASC);
CREATE INDEX IDX_DX_ERA_PERSON_ID ON CONDITION_ERA (PERSON_ID ASC);

CREATE INDEX IDX_DX_OCC_DX_CID ON CONDITION_OCCURRENCE (CONDITION_CONCEPT_ID ASC);
CREATE INDEX IDX_DX_OCC_DX_SOURCE_VALUE ON CONDITION_OCCURRENCE (CONDITION_SOURCE_VALUE ASC);
CREATE INDEX IDX_DX_OCC_DX_START_DATE ON CONDITION_OCCURRENCE (CONDITION_START_DATE ASC);
CREATE INDEX IDX_DX_OCC_DX_END_DATE ON CONDITION_OCCURRENCE (CONDITION_END_DATE ASC);
CREATE INDEX IDX_DX_OCC_PERSON_ID ON CONDITION_OCCURRENCE (PERSON_ID ASC);

